version: '3'
services:
  go-app:
    build:
      context: ./go-app
    depends_on:
      - node-app
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=db
      - DB_PASSWORD=root
      - DB_NAME=db
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - ./go-app:/app

  node-app:
    build:
      context: ./node-app
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    volumes:
      - ./node-app:/usr/src/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
