version: '3'
services:
  go-app:
    build:
      context: ./go-app  # The path to the directory containing your Go app
    ports:
      - "8080:8080"     # Map your Go app's port to the host
    networks:
      - mynetwork

  node-app:
    build:
      context: ./node-app  # The path to the directory containing your Node.js app
    ports:
      - "3000:3000"       # Map your Node.js app's port to the host
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
